USE dev
GO
SET NOCOUNT ON

DROP TABLE IF EXISTS dbo.Numbers
CREATE TABLE dbo.Numbers (num bigint NOT NULL)
INSERT INTO dbo.Numbers (num)
SELECT N FROM fnTally(0,10000000)

--ALTER TABLE Numbers ALTER COLUMN num BIGINT NOT NULL

ALTER TABLE Numbers ADD CONSTRAINT PK_Numbers PRIMARY KEY CLUSTERED (num)

