/***** DAY 4 *****/
/* https://adventofcode.com/2024/day/4 */
/* SETUP */

DECLARE @inp varchar(max) = 'XMXMXSXMMSSSSSXMMAMXAAXXMXSXMMSMXMXXMMMMMXXMXXAMSMSSSMXMXSAMXAMAMXSMSMXMXMAMAMAXAMSSSXSXMXMAXAMXSMMSSMXSXXSSXSXSSSMMSSMSXAMXXMAMXSSXSMXMSMMM
MMAMAMASXAAAXAAMASXMXMAXSAMAXAAAAXMASAAASMSMMMASMXAAXMMAASXSXMXASMAAXMAXSMMXSMMAXSAMXASMMSMSSXXAMXAAMXSAMXMAASAMAAXAAAAAXSASXSMSSMSASMSASAAX
ASASMSAMMMSMXXXMAMAMSMSMSASMMSSSMSAASMSMSAAAASXMXMMSMMAMASAMAMSASAMMMMXMSAAAAAXAXMAXMXMASMAAAMXSMMMMMMXAMAMMMMAMSMMMSMMMMXXMAAAXAAMXMASASMMM
XSAAXMAMSAMXASXMMSAMXAAASMMAAMAAAAMXMAXXMXMSMSAMXSMAMXAXAMAMAMMAMXXAMXMASAMXSAMASMMMAAMMMMAMSMAMAXAMSMSMSSSMASXMAAXAXAMXASXMSMMSMMMMMAMAMASX
MMXMASAXMASMAMXAXSMSMSMXMAXMXMXMMMMXAMMSXAMAMSMMAXMASXMSXSAMMSMXMXMMXAMAMXXAXXAAXASXSSXXXXSXAMASAMXSAAAAAMAXAMXSSMMMSMMMXMAMXXMSAAAAMAMAMSMM
XSAMXMAMSAMMAMSMMMSMMXMSSXMMXSAXMXMSMMAMSMSAXMAMXXSAMAASAMXSMAMSMSASMXMSSMMSSXMXMXMAAAASMMMSMMAMXXMMMSMSMSSMMXMXMXAXAAAXASXMMAXMSMSSSMSSSMAA
AXAXSXMASXXMAMAAAXAXMXMAMAXAAMAMSAXAAMSXSXSXSAAMMMMMSSMSAMXXXASAAMAMXMSXAMXMAXSMSMMMMMMMAAAAMMSSSSMXXMXXXAAAMSXMASXSMSMSMMAASXMXAMXXAMAMAMMM
MMSMMASAMMMSASMSMSMSSMMMSSMMSSMMSMXMSMXAMAXAMMMMXMXAMAAXMASMSMSXSMSMMMMSMASMAMMAXXAAAAASXMMMSXMAXAASMSMXMXXMMAXAXMMMAAXMASMMMMSSMSSSSMSSSMSM
XAAASAMAMAXSXSXMAAAXAMMXMMAXAAAXXXSXAMXAMMMXXAXXXMSASMMMMAXAAAMAXAXAXAAAXXMMSSMSAMXMMMMSSXMASMMMMMMSAAAAXMMSXMSMMAAMSMXSAMXXXXAAAAMAXAAAXAAX
MXSMMXSAXSASXXMMMMMXAMXAXMSMSSMMXXAXMSSMAXSASXXSAAMAMMXSMSMSMSMAMXMMSMSSSMSAXXAMMMSAMSMMMSMASAAXXMAMXMXXSAAXAXAASMMMXAAMAMMMSSSMMMSMMSMSMSMS
SAMAMMMMSXAXMMMSXASMMMSXSAMAMMAMMMMMMAXXMMMASXAMMAMSMMAAAMMXMMMMSSMMSMAMAAMMXMXMAAMAMAAAXMMMSMMXSMXSXSAASMMSMMXXMASXMMMSMMSMXAASMAAAMMAMAMXX
XASAMAAMSMSMAXAAMXMAAAAAMXMAMXAMAAXAXSSSMSMAMMXMMXMXAASMMMXASXMASAMASMAMMMMSMMSMMSSMMSSMMSAXSXSAXAMXAMMXMAMAMSMSXMAAMAAMXAAMMSMMMXSMMMSMMMAM
SAMXSSSMSAAMSMSSSSSSMMSMMMSSXSMSSSSSSMAAASAMXAMXMAMMSMXAASMMSAMXMAMAXMAXASMSAAAXMAAMAAAXASMSMAMMSMMMMMXAMXMASAAMAXMSSMSSMSSSMMAXSMXASXMAXMAM
MAAXXAXAMSMXMAXXAAMXXAMXAAXXMXMAMXAMAMSMMMXSMSSMSAXAMASXMMAASMMXSSMMMMXSMSASMMMAMSMMXXAMXXXAMSMAAAAXAMSMSMSMMMMMXMXXAAAXXMAXASAMMASAMMSMMSMS
SSMSMSMSMASAXXXMXMXXXSMSMSXMASMSMSMMAXXSXMASAMAAAMMSSMMAXSMMMXMMSAAMSSMAAMAMXSXSXXMMSMAXASXMSAMSSSMXSMAXAAAASXSMSAXSMMMSMMAMMSMMMAMAMXAMMAAA
AXAAAAAXMAMMMSMAMMMXMMASAMMSAAAAASASXSASXXAMXMMMMXAAAASXMAXMMAMXSMMMAASMMMAMMSAAAMSAMSAMMSAMMAXAXXXAXSSXMSMSASAAMSMSAMASXMASXMAXMMSSSSMMMXSX
MMSMSMSMMSXSAMAMAAMXSMAMAMAMSSXMASAMAMMXMMXSAXXSSMSXSMMAAXSMSASMMSMMSXMXXSXSAMSMXMMAXXMSXSAMSSMSMSMMMAMXMXMAMMMXMAMSAMASASAMASAMAAXMAAMSSMMX
XMAAMMMXAMAMASMXSMSAMMMSSMXXMMXXXSAMXMMAASASMMSAMXXAMXMASXMAMASAAAXAMMSMMXMAXXAXAMSMMAXMXSAMXMAAAAAXMXMMMAMXXAAMSMXSAMASXMAMXMXAMMMMSMMAAAAS
SSMSMAXMASAMAMMMMAMXSAMXAXSAMXXMASAMXMSASMASASMMMAMAMXXMMMMAMMMMSMSMMAAMXSAMXSMMMMAASXMSMSMMAMMMSMSXAASXSMMMSXSXAXMSXMAXMSSMSMXMAASAXXMMSSMA
XAMAMXXMXSAMMMSAMMMASMSMMASAMXXMAXMXAASMMMSMXMASMAMAMSXSAMXXMMAXXXXAMSMSAXAMXMXASASXXXMAXXASXSMMAXXXXXSAAASXMMMXMSMMMMMMMAMXAXAXSXMASMXXXAXM
MSMMMSXSAMXSAAXXSAMMXAAAXMXXMXMMMXSMMMXAXXAMMSXMSXXAMAAMMMSAMSXSSMXAMXXMAMSMMASXSAMXMSSMSMMXAAXSAMXMXSMMMMSXSAMASAXSAMXXMASXSMXMMAMXMAMMMAMX
AAAAAMMMXMAMMSMMSAMXSSSSSXSXSXSXXAAXXAXMMSMSAXXMAXMAMMSMMAAMXMAXAAXMXMMMAMXAMAXAMMMXAXMAMAXMMMMAMSMMMSAMXAMMMASXSAXXAXXMAMSAMAMASMMAMAMXAXMS
SSSMSSSMMMAMAMXMXAMXAAAAXAAASMSAMSXMXMMMMAXMXSMMAXSAMAXXMMMSAAAMMSXMAMAMSXSAMMSXXAAASXMAMSMXAAAMAAAAAMMMMASXSMMXMXMSSMSXSAMAASAMXMMSMMSMXMAA
MMMMXMAAXSXMASXMSSMXMXMMMMMASAMSMAASASASMSSMAMXMAMAAMXMASMASMSMXXMAMMSAXXASXMMAXSMSMXAMAMXXSMXSXSSSMXSAASAXAASXMXAMXXAXAAASXMMAXSMAXAMAASMXM
SXXSASMSMMASMSXXAMXAXSMSXSAXMAMMMSSMASXSAAMMAMAMMSMMMXMSAMXMAAXXSSSMAMMSMMMMSMMXAAXXAMSMXMAMAAMMMAXMAMMMSSMSMMMMSXMASXMMMAMMASMMAMAXASASAMXX
XAXSASXXASXMAXXSMSSXSAMXAXAMXXMSAMAMMMAMMMMSASXSMAMXXAMMXMAMMMMXMAXMXSMAAXXAAAXXMXMAMXAXAMXMSMSAMMMMAMSXMMMAAAXAAMMMMAXXXXXMAMAXMMMSMMMXMSSM
MSMMAMMXXMXMMMAXAAAXMMSMSMSMXSMMMSMMAMSMXMMSXSAXMAXMSSSMAMASXASMMSMXSAMSMSASXSMMXAAAMSASXMAMXASMMXMMAMMAMSSSMSMMXSAAMSMMMSMMSSSMXAXAMAMMXAXS
SMAMSMSSMMXAXMMMMMSSMXSXMAXXXXAAMAMSMMAMXMAMMMMMSXSXAAMMAXAXMXMXAXAMXAMXSAAXAAXASASMXXMAMSMSMXMXMAMSSMSXMAXMXMASASMSXXASAAAMAMXMSMSMSASAMSSM
MMAMXAMXAXSMXAASXMAAMXMAMSMSXMXMMAMAXSASMMAMAAAAXSAMMMMSMSMSSSMMMMAMSXMMAMXMMMSMMXAXXXSAMXMMAASAMAXAAAXMASMSMSAMASAXMSAMSXXMAXAMAMAXSAMXMXAM
SSMXMMMMSMMXSMMSAMSSMAMAMAMSASASMXSAXSAMXMMSMSSSSXMXSAAAAAAAAAMAAXAMAAXMMXSXAAXASMMSSMMMSSMMSXSXXSAMMAMXMAXMASAMXMAMAMMMMMSSSSMSASAMMASXMSAM
MASXSMSAMASASAXSAMXMMSMMSAMSAMMSAAMMMMSMXXAAXMAMXMMASASMSMMMSMSXSSMSSMMXXAMXMXSAXAXAXAAAMXAAMMMMMMAXXASMMMSAMSAMXMXMXMSAXAAAAAASAMXMXAAAAXAS
SXMXAAMASMMASMMSXMXMAXAASMXMAMMMMMMMAMASXMMSXMAMXAMASXMMMAMAMXSAMMMAAMSMMAMXSAMASAMASMMMSSMMSAAAASMMMXMAAAMXMSMMXAAXAMMMSMMXMMAMAMAXMMSXMSSM
MASMMMMXMXMAMXMSXSAMASMMMXAXAXAAXXASXSAMMXMXMXAMXSMASASAMASMXAMXMAMXMMAMXSMSMASAAASAMXXXAAXAMMSSXSMSMMSSMXSAMXSXSXMXXMAXMASXXMAXASMMXMMMMSAA
SAMASMMMXAMMMMAMASMMXSAMXSMSASMSSSMSMMMSMXMAXSASMMMMXAMMSAMXMMXASXSMMSMXAAMAMAMMSMMMSMSMSSMSSMXMAXAAMXAXMAXXSAMMSAMASMSMSAMMXSMSMAXMASXAXMXX
MASXMAASMMMSAMAMMMASXSXMXMXAMXMAMAXMASAAXSMAXSASXSASMMMMMAMSASAMXAAXAAAMSSSSSXSXAMAXAASXMXMAAASASMSMSMSSSSMAMXSASXMXXAAXMMMMAAXMXAMSXMMSSMMM
SAMXXSMXXMASXSXMASAMXMAMSMSSMASASMAXSASXSSSSMMMMASASXSMXSMMMAMXSMSMMSMSXAAAAXMAMXSMSMSMMMAMSSMSXMAMAAMAAAXMAMXMMSAMSMMMMMSAMSSMSMSMSAXXXAMAA
MAXSAMMSSXAMAMAMXMASXSSMSAAXSXSMSXMSMAXMMXMMASMMMMXMAXXAXXXMSMAMAXAXMMXMMMMMMMSMMMMXMXAASAMMMMMAMMMXMXMMMMMAXAXAXAMXAAXAXMAMXAXXAXXSMMXSAMSS
SAAMAMAAMMSSMSAMASAMXAAXMMMXAMXMMXXAMSMMSXMSAMXMXXAMAMMMMMSAMMAMXSAMXAXAMASAXXAAAMAMAXSMSMXMAAMAMMAMMSMMAMSMXMMMSMMSSMSSSSSMMMAMAMXMSAASAMXX
MMSXAMMXSAXAASASASASMSMMMAMXAAXMAMXMXXAAAMMMMSAMMMSMXXAAAXMASMMMXAMMMMSSMASMMSSSMSMSAAMXSASXSSSSSMMSAAASXXAMXXSMSAAMAAXMAAXAXXMAASXAMXMMMSSX
XAMMMMXMMXSMMMAMAXAMMAAXSAXSAMMMXMAMXMMMSMMAXSASMAXMASMSMXSAMAAXSAMXXAAMMMMAAXMMAAMMXSXAMMMAAAAXXAAMMSMMMMASAAXASXMSMMMMSMSMMXXSXAMMMSSMAMXS
MXSASAAXAAXXAMAMXMSMSSSMSAMSMSAAAXSXSXMXMAMSMSMMMSXSAXAAAAMASMMMSAMXMMSSSMMMXSAMSMSMMMMMMMMMMMMMMMMSXMASAMAMMSMAMMAMAAXAAXMASMMMMSMSAAMMXSAX
MASAMMMMMSSXSSXSAMXAMXAAMXMSASMSMMAAXAMXMSMXAXXMAXMXAMSMAMSXMAMMSAMXMXXAAXAXASXMAAAAAXAXXXAXMXSAMAAAMSAMXMXSAMMAMMASXMXSXXSAMAAAXAAMMMSMSMMS
XMMXMXXASMXAMAASXMMMMSMMMAAMAMXXXXMMMMMMXXAMAMAMXSXXMMXXMXSASXSASAMAAXMSMSSSMMSMXMSSMMMSASMSMMSASXMXAMXXXMXMASXMXSXSAMAAAAMMMSMMSMMMSAXMAAAX
SAMXMSMMSAMSMSXMAMXSAXXASMSMSMMMSXXSAMXXAMAMMMSMASAMXAXAAAXAMAMASAMXMXMXAAXMAASMSAMXMSSMMMAXMASXMAXSSMSXSASMAXAXMMXSAMSMAMXSAXAMAXAAMASXSMMS
MASMMMXSMMMXAMSSXMAMAMMXXAXXXXAAXMASASMMXSAMAAAXASASMMMSMXSAMXMMMXMAXSXMMMSMMMSAXAMAMXAAXMAMMASMXMXAXAXXMAAMAXMMAMASAAXAMXXMASASASMMMMMXXAAX
SAMAAAXMAMAMAMAMAMMSAMMSMMMSMSMSXSMMAMXAMSMSMSMMXSAMAAXXAASAMXSMMMSXMMMAXXXXSAMXMXSASMMMMSMXAMXXAMMMMMMMMMMMSSMASMXSMMSMAXXMAMXMAMMASASMXMMS
MAMSMSMSAMSSSMMMAMMMMMAAAMAAAAAAASXMAMMSXSASXMAXXSASXMAMMMXXMAXAAMAMAAAMMMAMMAXXMXSXSAAMASXMSAMMXXAAAXMMAXAAXXMAXAMXMAMXMSMMMSMMMSSMSAXASMAX
MSMAAMAMXSAAXXSSSSXAAMXMMMSSSMSMSMASASAMAMAMASXMXMAMMAMXMMMMMMSSMSXAXAMSASAMSXMASAMXSMMMMMAXMASAASMXSAMXSXMMSMMSXSAAMAMAXAXAXAMSAAAXMMMMAMXS
AAAMMMXMMMMMMAMXXMMMSMMASAMAAAXXAMMMXAMMMMAMXMAMMMSMMXXAASMXSAAAAAMSAMASMXAMAASAMASXXXXXMXMMSAMMMSAAAXXXMXSAAXAMXASMMSMSSXXSMSSMMSSMMXSAAXAA
SMSMMXAMAMXAAMMSMMASAXAAMAMSMMMSXSXSMMXMXSXSASXMMAMAMSSXSXAAAMSMMSAMSSXMMSSMSXMASAMMSMMMSAMAMXMXAMMMMMMAMAMAMMSSMMMMAXAMMXAMXMAXAAMMAAMXSMMX
XMMAXXSSMSSMSAAMAXMSASMXXXMAAAXSASMSXMAMMMASASAMMAXMMAXXMMMMMXXAMXMXAXAAAXMAXMMMMAMXAAAASAXSXSMMMSXXAMXAMAMXSMAAXXMXAMAMAAMSMSAMXSAMMXMAMAAS
MASAMAAAMXMAMAMSSMXMAMXSXSMSXMSMAMXMASASAMAMXMASXSXSMMMSMSASXMASXASMSSSMMSMMMSAXSAMSSSMXSSMXMMMAXMAXSMSXSASAAMSMMAXMSSSMXMMAAMXMXMXXSAMXSAMA
MXMAMXXXMAMMMAMAXMXMXMASAXAAMMXMAMASMMASMMAMSSMMAXMMAMSAAXSMAAAXMASAXAMMAAAAASMMSAXXXXXXMASMASXSMMSMMASASAMMMMXMMSAAMAXMASMMSMSMXMSMSASASAMM
XAXXMMSMMSSXMXSXMMMSAMXMAMSMSXAXXSASAMXMMSMSAAAMAMASAMMMMMMSXMASAAMMMAMMSSSMMSXXSMMSAMXMMXMSXMAAXXMAMAMAMXSMXAMXAAMMMXMMXSXAAAAMAXXASAMXSASX
SMXSXAAAXAAMSMMXSAMSASMMSMAAAMAMXMASXMMAMAMMXMMMMMAMAXXASXMASXAMXMMXMAMXAAAXAMXAXAXAAMSXXAAMMXSMMSMMMMMXSASMMSSMSSSSXMASMMMSMMMXXSMXMSMASAMM
AMASMSSSMMSMAAMAMAXSAMXAAXMSMASAXSASXMAXSXSASXMASMXSAMSMMMSASMMSAMXAMXXMXSMMXSMMSMMMXMAASMSMSMXAXXXXAASMMXSAAXAXAMAMAXXMAXAXMASXXMASMMSMMXMX
XMASAAMXAXAMXMMMMMMSXSMXSSMAXSXXMMASASAXSXMXSASAXAAMAXAAAAMAXXAMAXSASAMMMMAMMMXXAMAMXMMXMAAMAASAMXXSSMSASMMMSXMMXMAMXSAMSMSMSASAMXXAAAMXMASX
XMAMMMSMSMSSMSAXASXMAXAAXAXSSMMSSMAMAMMXSAMAMMMSSMMXMMMMSSMSMXMMAMXMAXAAAMAMAAMMMSAXMXSAMXMSMMMXSXMAMAXXMAMMMAXAXXXAAMAMAAMAMASAMMASMMXAMSMS
XMAMSASAAXXAAAASXXAMXMMMMAMXAASAAMXMMMSASAMMSAAXMASXSXXAXXAAXMXSAMXMSMSMXSAMMSSSXSASMMSASXMMXMSAMMAMMSSSSSMASMMMSSMMXSAMXSMAMAXMSSMXAMSMSAAA
MSASMASMMMSMMMXAMSMMAAAMMXMSSMMMXMMSAAMASXMASMSXSAMXAAMSMMSMMSASASMMAAAXMAMMSAMXAMAXXASXMAAAMXMAMSSXMXAAAMMMMSXAAXAAAXASXMMMMMSAXAXSXMAMMMMX
AMMSMAMXMAXAAXXAAAAMASAMSAMXXMXSSMAAMXMASXSMXAXASMMMMMMMAXAAXMAXAMXMASXMSAMXXMSMXMMMMXMMXSMMSXMXMAMAAMMMMMAXSSMMSSMMXSAMXSAAAXMASMMAMSXSXSXM
XASXMASMMXXSMXMAMSMSMMAMMAMAMSAXMASXMXMXSXAXMXMASXXXXAAXMMMMSMSMXMASMXXAXXXAMXXAMXAAXMXAAXAMXMSMSASMMSMAXSMSSXXAAXAAAMAMAMXXSXXMAXXMMSASAMMS
SXMXSASXMSAXSXSAAXAAXMAMXMMASMMSSXMASMSMSMMXXMMAMXMXSMXMAAXXSAMMXXMSAMXSMMMSXSSSSSXXSASMXSAMAXXASASAAMMMMSXMXAMMMSMSMSAMXSSXMASXMXSXMMMMAMAX
SAMMMMSAMXAMAMSAMMSMSSMMSXMXSXAAAASAMASAMXXXSXMASASXXAASXMSAMAMMSMXMMMAAAXXMAXXMAXXXAMSAAXASMSMXMAMMMMAMAMAMMXSAMAAAXMASMAASAASASAMXMAMSMMSS
MAMXAXSXMMMMAMXXXAXXMMAAAASAMXMMSMMSMAMXMMMMMASASASMMSMXAAXAMMMAAXMMMMSSMMSMMMASASMMMXMAMSMMAXAMMMMSMMMXAXAMXASASMMMSXSMMSMMMXMAMAMAMAMAXMAS
SSMSXMMMSASXMXMMMMSASXMMSAMAMASXAAXMMASAMAAASXMMSMMAMMASMMXMMAMMSMMAXMXMXAAMXMAMAMAAXSAMXAAASMSMSAAAAASMXSASMASAMXMXSXMAAXXMASMAMMSSSXSSSMAS
AMASMAAMXASMSAMSAMMAMMXMMMSMSASMMSSXSASASMSMMAMXXAXSMMMMMASASASMAMSAMSAMMSXXMMMXXXSMMMAMSXSMMAXAXMAXMXSAASXMAMMAMXXASXSAMXMAAXXAMMAXMMMMAXAS
XMAMXMMSMAMAXAMSASMMMMASMMAAMASAMAMMMMMXMAXMMMMMMSMMMASAMXAASMXMAXMAMMAMAMMSSSSXMAXXMASMAMMAMMMMMXMASMSMMMMXSASAMXMASASXAAMMASMMSMMMSAMXAMXS
AMASXSASMAMMMSMMAMMSMSAMAMMSMMMMMAXSASMSSXMSAMXSAMASXMMXSSMMMMXSMSAMXSSMASAAAAMAMSMMMMMMAXXAMSSMMMSAAAMAXXXAAXSXMXAMMAMXSAMSASAMMASASASMSSMM
ASMMXMAMXAMXAAASAMXAAMASXMXAXMAXMAMMASAASAAXXSAMXMXMAMMSXMASAXXSAXXXXMASASMMMMMXMAAAAAXSAXSAMASAAASXMMSSMMMXXXSASMSMMSXMASXMASXMSAMAMAMAMMXM
MXXSXMAMMSSMSSXMXXXMMMXSXAXMXMASMMSMAMMMMMMSSMMSSSMMSAXMASAMXSAMAMAMMXMMXXAXSXSAMXMXXMXMXXAAMASMMMSASAMXAASASXXAMAXXAAXSAXXMMMMAMMSSMAMSMMAS
XAAXAMAXMXAXMMXMMXAXSAAMXMMXMSXSAASMAMXAXXAXAAAAAAAAMXXXAMXSAMMMXMXMMAXXXMMMMXMAXSXSSXSXSSMSMXMXMASAMXSMXMXAAMMSMMMMXSXMMSXXMAXXMXAMSSSMASAX
MMSXXMASMSSMMMAAMXXMAMXSAMAXAMAMXMXSMSMXSMASXMMSSSMMXMSMXSXMXSXMXXXASXSXXSAAXSXMMXAMAASAMAXXMASXSMMXMASMMSMMMXAMASAXXMAAMMAAMAMSMMXMAMAMAMAS
XAAXMMXAMAXMAMXAMXMAMXAXASASXMAMASXSMMMAAMMMXXMAXMASAAXXAMXSAAAASXSMMAMMMSASMXASAMXMMMMAMAMAMXSMAXMSMAXSAXAAXMASASMSASMMAMSMMXMAASXMMSAMXSXA
MXSAXSSMMSSSMSSSXSMASAMXAMASMMAXASMXAAMMSMAAXXMASXASMSMMMSAMMSMMAMMAMAMAMMXMASXMSAAMASMMMSSXMMMMSMXAMAMMMXAMXXAMASASMMSMMAAAXMSSMMAAXMMSASXM
SAXAMXAMAMXXSAMXAXMASAMMMXAMMSSMXMAXMMSAAXMSSMSMMMASMXMAMMAMAXAAMAXMSXSAXXAAMXMAMSMSAMASAAAAXXAAXXSXSXMASXSSSXAMAMXMAXXSMXMASMAMMXXMSXAMASMX
MASMMSXMAXMXMMXMMMMMSMSASMSSXAXASMSXMMMXSSMAAASASMSXMASMMMAMSSMMXSMXAXMMXSMSMASAMAMMXXAMMSSSMMMSXXMASXMMSAMAMMSMMMASMMMXMAXXXMASXSMASXSMMMXX
MXMAXSXSXMXAXSASAXAXMASASAMXMXSAMAMMSXMMXAAMXMSAXMAAMAXMAMSSMAMMXMAMMSMSASAAMMMASAMAAMMMMAAMXMAMMXSASXMMMAMSMAXAXXAXMAMASMMSSMXSAAASXAXMAMXX
SMSSMMAMMSSMMSAXASMMMAMMMMMAXAAXMAMAAAAMXMMXMMMMMSSSMSSMAMXAMAMXAMXAXAAMAMXMXMSAMXMMMSAAAMMXMMASMASMSAXAMMMMMSSSMMMSSMSASAAMASMMMSMMMXMMAMXM
AAAMSMAMAAAMAMMMXMXAMXSMMXSSMMAMMASXSXMSSSMXSXAXAMAXMMAMMXSAMSSMMSAMMMSMSMMSAAMAMXXAASXSMXXAMMAXMASASXMSSMAASAMXAAAAXAMXSMMSMMXAAMASAXSMASAA
MSMAASXMMSSMASAMXASXMAMMSAAXMXAAXAXXMAXAAAAASXMSMMMMMSAMXAMMMMAXAAAXAAAAXAAAMMMMSXMAXXAXMMMXXMMSXAMAMXXAAXSMSAMSXMMMSMSAMXAAMAMMXXSMSAXSAXXS
XMXSXSXAXAXXAXMXMAMSAMXAMMSMSSMSMXMASMMMSMMMSAMAXAXSASAMMSMSAMSMSSMMSSMSMMMSXXAAMMMSMMMMSSMXSASAMXSSMSMSAMXXXAMMASXMAXMXSMMXMXMAXXAAMMMMMSMM
XMXMAXXAMXSSSXSAMSAMXXMASMAXAAAXASXMMAMXAAAAMAMXSASMAXMXXMASXXXAMMAXAAXAXXXAXSMMAASASAMXAAAAXMMAAMXXAXAMAASMMSMMAMASXSMXSMMSMMXAMSMMMXSAMAAA
MSSMMMXXAXMAMAXAMXAMMSMMMXMSSMMMXMASMMMSXSMSMSMMXMXMXMMAMMMMXXMAMSAMMXSXMMXMMXMXXMSASXMMSSMSSXAMMSMMXMXMMXMAMMAMSSXMAAXAMXAAASMSMASXMASASMSS
SASAXAMXSMMAMSSSMSXMAAAMMAXXXMAXXMAMAXAAAMXMAMAMASASMSMAAASMMMSAMXXXAAXAMXAXXAMXSXMXSASAMXAMXMXSAXAXXMAMAXMXMSAMAXMMSMMXSMXSXMAASXMXMAXMMAAX
MAMMXSAMAAXMXXAXAXSMMMSASMSSSMSMAMXSXMMSXSAMXSAMMSASAASXXXMAAAMMMMXMMMSAMAMSMAXSAXSASXMASMSMXSAMAXSAXSAMSSMMXSMMMSAAMMMMXMAXMMSMMXSXMSSSMMMS
MAMMAMMSSSMSXMMMMMASXAMASAAAAAASAMMMMXMXMXAMXMXMASMMMMXMSMSMMSSXSMMSAAXMMAAXXAMXMXMAMMSASAMAMMASAMAAMMMXMAASAXXAMXMXSAAAXMASAXXAMXSSMMAXXAMA
MASMASAMAXAMXXAAXSAMMSMAMXMXMMMSXXAAMXMAMXAMXMSMXSMSXMAAAMAAXMAMAAAMXSMSSSSSMSASXMMSMAMAXMMSMSAMXSMXMAXAMSMMMSSMSAMXSXMMXMASMMXAMAMAMMAMSXSS
SAXAAMAMMMSMMSXXXMAMSAMXMMSMXSAMAXSXSASASMSAMXAMXSXSASMSMSSSMMMAMMMSMMAAAAAAAAAAASAXMSMMMSAXMMMAAMXSSMMMXAXMAMAMXAMXMMXMAMASMMSSMMXAMMSMSAAX
MMSMASXMXAAAXAMSSSXMSXSAMAXAXMAMMMXASASASXMAMMAXXMMSAMXMXMXMAAXSXSAXAMMMSMMMMMSMXMASAMAMAMASXAMMMSAMASASXMMSMXAASAMAMASMAAAXAMAMXMXASXXAMMMM
XXAXMAXXMSSMMMSAASAMXMSMMAMXXSSMSSMAMAMXMXSAMXSMAMAMXMAMXMASMMSAMXMSSSXMMMMXXAXMAMXMMSAMASMAXXSMAMXMMMMMAMASXSMMSAMMMAMSAMXSSMASAXMMMXMAMSAA
MSMXSAMMAMAASXMASMXXAXXMMSSMAXXAXAMXMXMASMMAXAASAMSSMMAXMSAMAXAXAAAMXMAXXAMXMMSMSMAXXSASXSMMSMMMSMMSXMASMMAXXMAASXSXMAXAXMXAXSAMAXSAXASAMMMS
AMAAMASMASMMMMXMAXXSSSSXAAAXSSMSMSMSMASASXSAMXXMSAMXASASASAMXMSXMMSSSSSMSXMXXMAAAMSMMMXMASXSAAMAMAAAMSAMXMAMMXMMSAXXMXSMMSMSAMXXAASMMMSXXSAM
SMMMSAXMMSMSMAAXMAXAAAMMMSSMMAMAAAAASXMMXAXAXSAMMXXSXMAAASAMAAAMSMAAAAAASMSXASMMMXXAAXMAMXSMSSMASMMMXMAXXMAXSASMMAMSMXMXAXSMMMSSMMSXMASAMMAM
MASAMMSSMSMAXSMMMXMMMMMAAXAMSSMMSMSMMXMASXSAMSAMXAMXXMAMMMXSSSMSAMMSMSMMMAXMAXMASASXMMSMSSSMAXMAXXXXXSXASMMAAAMXMXAXAAMMSMMXAAMAMXSMMMMAMMSM
SAMXSAAMASXMXMMASASXAAXXSSXMAAAAXAAMSMMASXAXMMMMMSMMMAMXAAAMXMXSASMXXMXXMMMSXMXAMAMAMAASXAXMAXMAMSSMXXMAXAXMMXSXMMMMSMSAXAMSSMMMMAXMMXSAMXAS
MXSASXXMAMAXMASASASMSMMSAMXMSSMMMXMMAAMASMMSSXMAAAAXSSSSMSMSXMASAMXSASAMSMASASMXSSSMMSSSMMMASMMAMAAXSASXSMMXXAMAXAAAMAXASMMMAMSXMSSXAXSAXMAS
MSMASXMMSSSMSXMXSAMMXAXMAMXMAXASMSSSMSMAMAMAMASMSSXMAAAXAAXMAMASAXAXMMXMAMXSAMAAAXMXXXMMAMXSAASXMSMMMAMAAMSMMXSSMSXSSMMMMXAXAMAASAMXMMXSMMSX
MAMMMMMAAMAMXMMMMAXAMAXMAMAMAXMXAAAAXMMMSMMASMMXMAMSMMMMSMSSMMMSAMXXSMSXXMAMXMMMSSSXXMAXAMMMMXAXAXAAMXMXMMAASAMAAXXMAXAXMXSXMXXXMASMMMAXXXMA
SASASAMAMMAMAAAXSMMXSSXMAXASXSSMMMMMMXXAAAMXXMXAMXMXAAXXAAXXAAXSXXAASASASMMXSAXMAAMMSSXXASXXMMMMXSSMSAMXXSXSMASMSMMSXMSMSAAASMSMMMMMAMASMMMM
XASAMXSXXXAMSXMMSXAXMAMSSSMSAMMAMXSMXSMMSXSASXSSSSMSSMSSMSMXSSXMMMMMMAMAMXAXMSSMMSMAXAASMMXMXMXMXXXMAXMXMMSMXXMAMMASAAAAMMSMMAAAASASXMSAMXAX
MXMXMMXASXMMMSMAXMSMMSMMXAXMASXSMAAMASAAAAMAMAAMAXMAXXMMMMXMAMAAMXSXMXMMMMMXSAMAAXXMMMMMXAASASAMASAMXAXAXSAMSXMXMMASMMMSMAMXMSMSAMASMMAMXSMS
SAAXMXSXMAXAMAMMXAAMAAAMMAMSXMAAMSSMASMMXMMAMMMMAMMAMXXAAMAMASXMMAMMMXMAXAXXMASMMSAMSSMAMSMSXSXSASMMXMSAXSAMXASXXMXSXXXAAASXXAAXAMSMMSSSMAMS
SMSMXASAXXMAXMMXMSSSSSMMASXSXMMMMAAMASXXSASXSSXMXSMSSSSSSMXSMXXSMAMAMXSXSSSMXXMAMMAMAAXXMMAMXXXMXSAAAMMMMSXMSMMMAMSMMSMAMMSXMMSMMMXAMAAXMAAS
XAAMMXSAMSASXXSAMMAMAAASXMAMSMMAMXXMAXAASMMMAXAMXSAAAXAAAXXMMSSXSSSMSASAAXXASMMSMSMMSSMSXSASMMSXAMMMMSAXAXMAXAASAMAXMAXAMMXMASMAXASMMMMMSMSX
MSMSMXMXMXAMMMMMXSAMMMMSAMXMAMASXSAMXMMMSXMMASXMAMMMXMMMMMAAAXMASMAAMAMMAMMXMAAXXXAAXAXXAMAMAMSMSXAAAMAMXSXSSSMSXXXSXMSMSMAASMSMMXSXMXAMAMMA
MAAAMAMSSMMMXXAMMXAMXXXSMMXSMSAXAMXAXXSAXAXMASMMASMSAXXAXSMMMXMXMSMXMAMXMMSSMMMMASMMSSMMSMMMXMXAMAMMMSAMMMMMAMXXMAXSMMAMAXMMMXAMMMMAMSMSAMXX
SMSMMASAAAAAXXMSASMMMMMMAMXXMMASXXXXXMMMSSMMASAMXSAAXMMMXSXMMXSXMASAXASAAXAASAMMMMMXAMAAMAMXMXMXMAMAASAMAAXMAMXAMXXMASMSAMSASXSSXXMAMMXSAMSX
XMAMMMSMSSMSSMAMASAAAXAAASXAXMAMASXMXSAXAAAXAMXMAMMMAAXMMSAMMMMAXXSMSMSXSMSSMXAAAAXMASMMXAMMXXMASASMXSASMSMMXMMXXMASXMAMXXSASAAXMMSSSMAMMMSA
XMASXAXXMXXAAMAMXSMMMMXXMSXMMMMSAMXSASXSSSMMSXXMAXAXMXSAAMXMAASXMAXXAXMMXAMXXSSSSMSAMXAASXMAXSXMSASMMSMMAXAMAXMASAXMAMMMSASAMMMMAMAMXMAMAASM
XMAMMSMASXMMXMAXXMXSSXSMMSAMAAXMXSAMASAMAMXAAMSMMMSAAAMMMMASXXAAMMMSMSXAXAMMXXMAXAXXAXMMAMXSXSAMXAXMAMAMASAMXSMAMSAMXMAMAAMAMXAASMASXMSSMMXM
SMASAXMAMMMSMSSXSXAMMAAAAXAXSSXSAMASAMAMXMMMXXAAXAAMMMSAAXAMXMSMAAXAASMMSAMXSMMMMMMSMSXAMAXXAMMMSMMMMSXMMMXMXXMAMMXMASXMMXMAXSXSASASMMMAMXSM
XSAMXSMXSAAAXAAASMMSSSMMSSSMAAAMASAMXSXMSXMAMSSXMMSAMXMMMSASXAAMMMSMMMAXAMMASAAXAXXAAMMXMSMMAMSMSAAXMXMXAMSSSMXSSMAMMSSXSMSSMXMAXMXSAMSAMAAS
MMXMAXMASMMSMMMMMAMMAXXXAAMMMMXSAMASMSAMMAMMMAXASAAAAXMAMSAMASXSAMAXAXXMSXMXSXMXXXSMSMAAAMAMAMAAXSMSAASMMSAAAAAMAXSMMXMXSAAXMASXSMMMMMSAMAXA
ASAMXSAMXMAMAXAASXMMMMMSMMMSXXAMXSAMXXAXSASMMASMMASXSAMXXMAXXMAXAXAXMSMXXASXMASMSMAAXXSXSSSMSSSSMXXAMSSMMMMSMMMSAAXASMMAMMMMSAXAAAXMSASMMSMM
XMAXAXMASMASAXSXSAMAXAMAAXAXMMMSAMMSMSXMXASAMXMMSAMXMXXXXMMMSMXSSMSXMAAXSMMASASAAAMAMAMAAAXAXAAAAXSMMMMAAMXXMXXMMMSAMAMXXAAAAMASMMMXMASMAMAS
SSSMSSSXXMAMXMMXMASXMXMSAMXSAAAMASAAAAMSMMMXMAMXSAXXMASXMSMAAMMAAAMMSASMSASXMASXMMSAMAMMMMMXMMMMMMXAAAXSMSAXMAXXXAXAMSXASMMSAXXXAAASAMXMAXMM
MAAAXMMMSMMXSAXASMMXAMXMASAMXMMSSMXSXSASAMAASXSASXMXMAXXAAMSMSMSMMMAMAMAXAMMSXXAXXSASXSAMXXASAXXXXMMMSMMAMASMXSSMMSXMXXMASMXXMASXMMMMXSXSSSM
MSMMMAAAAXSXAAXAMMAMXAAXMMAMXSMXAAMMMMXSAMSXSAMAMAAXMSMMSMXMAXXMAMAAMAMXMMMXMMMMMXSAMXXASMSMXXSMMMSAAXAMXMSMMMMXAXAASXSXAMXMSMMMXMAXMASAXMAS
XXXASXMSSSXMMMMSMMSSMSASXSXMAXMSMMMSXMASXMMAXMMMSMSMMAAMMMXMMMMSMMSSSXSAMSSMXAAAMXMMMMSMMMAMMMAMAAMMSMXMAMMAXSSSMMMSMAXMXSAMAXAAAXXSAAMXMSAM
XSAMXMMMMMAMXSAXASMAAXAAAAMMMXAAXAMXAMAMMXMXXMAXAAAMMSSMASXMAMMAMXAAAASMXAAXXSSSSMSAAAASMSXXAAASMXSAMXAMAMMMMMAAAASAMMMSMSASMXMSMSAMMSMMAMAS
AAMAMXXSASXMAMXMMMMMMMXMAMAAAASMSSSSSMAMMAAXMSASXXMSXMAXAMXXAMSAMSMSMMSXMSSMXAAAAAMSMSMSXSASXMMXAAMXMSXXSXXAAMXMMMMMSAAAASAMMSMAMXXMAMAMSXXM
MAMSXSASAMXMSSMMSAAAAMAXAXSASXMAAAAAAMAMMSSMAAAXXASXMSAMXXSXAMMAMSAMAMXMMXAXAMMSMMMXXAAXAMXMMASMMMMMMSSMXASMMSASMSMXSMSSMMXMAAMXSSMMASAMMSSX
XSSXAAAMXMXMAXAAMMXSASMSSMXAXXMMMMMMSSMSMXMASMSMSMMAMAAXMASMMMSAMMMMSXMAMSMMMXMXMMXXSAMMSAMXSAMAMXASAMAMMAMXASAXAAAMXMAXAMXMSAMMMAAAAMAMXAMX
XXAMAMAMMSAMMMMSSMAXAAXAMAXMMMXXXXSAMXAXMASXMAAMXAXAMMMMMAXAAAAXSXMAMAAMASAMXAMAMXSMMXMXXAMAMASMMMMMASXMMAMMAMAMSMSMAMAXXAXMASAAXSXMASXMMMMX
XXMMMXAAAXXXXAAAAMAMSMMMMSXAAXMAMSMMSMSMSASAMSMSSSSSSXSAMXSSMSSMXAAASAMXASAMSMSASAAAAAXSSXMASXMMASXSXMAASMXAMMXMMAMXXSXASMSMAAXSMMXXMMAMMMMX
MMXASXSMMSSSSSSSSMXXMAMSAXMSMSMSMSAMAXAXMXSAMMMXAAAAAMSAXAMAAXMASMMMMASMXXAMAAXAMMSMMXXAAXSAMAMSAMMXMXSMMMSSXMAAMAMXMAMMXAAMAMMMMXASXSAXMAMS
AAMXSAXSAAAXMAMXAAXMSAMMXSXMAXAAASXMASMMMASAMXMMMMMMMMSMMSSMXXAMMXAAXAXMASXMMSMXMAMMASMMMMMAXAMMASAXAAXASAAMASXSSSSXMXMXMXMXSSMASMMSASAXSAMM
SSSSMMMAMMSMSMSSMMSAMXMMASAMXMSMMMAXAMMSMASMMAMMSXMMSAXXAXAAMMMSMSXSMMMSAMXAAMAMXSXSAAAAASXSSXSMXAXXMASAMMSMMMAAAAMMMASMSASXAAMAMAMMMMMMXASX
XMMAASMSASAASXMAAAMXMAXMAXAMXMXMAXAMMMAAMMMXXAXXMASAMAMMSSXMAAMAMXXMAMXMAXXMMXAMAMAMXSSMSAAXAMXMAMSMSMMXMAAASMSMMMSAMMSASASMSMMSXMSAAAAXSMSM
MXSSMMAXSSMSMASMMMSASMSMMSSMXSASMSSXSASXXSASXSSSSMMXSASAMXXMXXMASXAMAMXSXMXSXXSASMMMAMMXMAXMMAAXAXAASMXMMMSSXAXXMAXXSXMAMXMAMXMXASXXMSMXAAMX
AMXASMXMAXMXMAMXAXSAMXAAAAAMXXASAAAASMXMMMASAMXAASMASAMXSASMSXSASMSAASAMMMXMASMAXAASASASMSAAXSMXMXMXMASXXAMAMSMMMXSAMXSAMXMXMMSMXMAXXAMSMMMX
MXSAMMAMMMSSMMMMXMXXMASMMSMMSMMMMMMMMXMSSMMMAMMXMMXAMMMMMMSAAAXASAMSMMMSAAAMSMMSMSMSAMASAMMXAAMAMXMXMMSMMSMSAAAXAAMAMMSASXMASAAAAXAMMAMMXMAX
AMMSMSXSXAAMAAAMSSSMMAMXAMXAAAXMMAMAMMMAAAASAMMSMSMSXMAAAMMMMSMAMMMAXASMXSXSMAAXAAXXAMSMXMXMSASASAMASXXAAAXASMSMMSMMMASXMAMSMSSSXMMXSAMSMSSS
MXAXMAXXMMMXMMMSAAASMASMXSMSXSMMMAMAXAMSXXMSXSAAAAAMMSMSMSAMSAMXMXXAMXMMMMMAXMMSMSSMMMXAXMXXXASXSXSASASMMSSXXMXAMXASMMSASXMAAXXMXMMASXMAMAAS
XMXMXMSXSSSXSAXMMMMMMASXASXMAMAASMXSSSXXAMMMMXXMSMMSASXAASMMMXSXXSAMXAAAAAXSXMAMAAMAAXXMSMSMSMMMSAMASAMAAAAMMMMSXSMMAMSXMASMSMMSMSMASASMSMMM
MMAMAMAAXAAAMAMXSXMASAMMXXXSASAMXAAXXMAMMMAAXAMXXMASAXMMMMSSXMXMASASXXSSSSXMASAMXMSAMSMMAAAMAAAXMXMAMXSXMSMAAXAMXMASMMSASMMXAAXAAAMMSMMAAAXM
ASASASMMMMMMMMSAMASASAMAMSMMAMMMMMMSAMXMXSSSMXSAMXMMMMMSXAASAMXAMSMMAMXAMXASAMXSSXSAMXMSMSMSSSMSMAMASAMXMAMSSMMSAMXSAMSASXMSSSSMSMSAMXMMSMMM
XSASMSAAMXAXXMMASAMASXMAAAAMAMAAXASAMXAMAMAAAASXSAXASMAAAMXSMAXSAMXMXXMAMSAMASXXMASAMSXAAAXXAAXMMASMMMSASAMAAMASASASAMMXMAMXMAAAAAMXSAMXXMAM
MMXMXSMMSASXMASXMASMMXSASXSMXSXSSMSMXSSSXMSMMMSAMXSMXMAMSAMMASAMXAXXASMXMASMMMXAMXMAAXSMSMMMSMMXSMSXMXSXSMMMSMXSAMASMMSXSAMXMMMSMSMXSXSMASMS';

/**** TEST */
/*
DECLARE @inp varchar(max) = 'MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX'
*/

--SELECT  @inp

DECLARE @CRLF varchar(10) = char(13) + char(10) ;
DECLARE @inStr varchar(max) = REPLACE(@inp,'mul(','|')

SET @inStr = REPLACE(@inStr,@CRLF,'|')

--SELECT @inStr

/* Part 1 */
/* Instructions table. */
DROP TABLE IF EXISTS #tmpInstructions
CREATE TABLE #tmpInstructions (id int identity, instr varchar(max), rowNum int
, charsLeft varchar(5), charsRight varchar(5), charsUp varchar(5), charsDown varchar(5)
)

INSERT INTO #tmpInstructions (instr, rowNum)
SELECT value, ordinal FROM STRING_SPLIT(@inStr,'|',1)


/* Instructions2 table. */
DROP TABLE IF EXISTS #tmpInstructions2
CREATE TABLE #tmpInstructions2 (id int identity, instr varchar(max)
, rowNum int, colNum int, charVal varchar(5)
, charsDiagUpLeft varchar(5), charsDiagUpRight varchar(5), charsDiagDownLeft varchar(5), charsDiagDownRight varchar(5)
)


/*** GENERATE_SERIES FTW! ***/
; WITH s(n) AS (
SELECT value FROM GENERATE_SERIES(1,250,1)
)
INSERT INTO #tmpInstructions2 (rowNum, colNum, charVal)
SELECT t1.rowNum
, CASE WHEN (s.n%LEN(t1.instr)) = 0 THEN LEN(t1.instr) ELSE (s.n%LEN(t1.instr)) END
, SUBSTRING( instr, (s.n),1 )
FROM #tmpInstructions t1
CROSS APPLY s
WHERE s.n <= LEN(t1.instr)

--SELECT * FROM #tmpInstructions2 ORDER BY id

/** PART 1 **/
/*
SELECT SUM( ls+rs+us+ds+uls+urs+dls+drs ) AS xmasCount
FROM (
SELECT s1.rowNum, s1.colNum
, CASE WHEN leftString = 'XMAS' THEN 1 ELSE 0 END AS ls
, CASE WHEN rightString = 'XMAS' THEN 1 ELSE 0 END AS rs
, CASE WHEN upString = 'XMAS' THEN 1 ELSE 0 END AS us
, CASE WHEN downString = 'XMAS' THEN 1 ELSE 0 END AS ds
, CASE WHEN upLeftString = 'XMAS' THEN 1 ELSE 0 END AS uls
, CASE WHEN upRightString = 'XMAS' THEN 1 ELSE 0 END AS urs
, CASE WHEN downleftString = 'XMAS' THEN 1 ELSE 0 END AS dls
, CASE WHEN downRightString = 'XMAS' THEN 1 ELSE 0 END AS drs
FROM (
/**** UGLY QUERY *****/
SELECT t1.rowNum, t1.colNum
, CONCAT(t1.charVal, s1.charVal, s2.charVal, s3.charVal) AS leftString
, CONCAT(t1.charVal, r1.charVal, r2.charVal, r3.charVal) AS rightString
, CONCAT(t1.charVal, u1.charVal, u2.charVal, u3.charVal) AS upString
, CONCAT(t1.charVal, d1.charVal, d2.charVal, d3.charVal) AS downString
, CONCAT(t1.charVal, ul1.charVal, ul2.charVal, ul3.charVal) AS upleftString
, CONCAT(t1.charVal, ur1.charVal, ur2.charVal, ur3.charVal) AS uprightString
, CONCAT(t1.charVal, dl1.charVal, dl2.charVal, dl3.charVal) AS downLeftString
, CONCAT(t1.charVal, dr1.charVal, dr2.charVal, dr3.charVal) AS downRightString
FROM #tmpInstructions2 t1

/* LEFT STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) s1 ON t1.rowNum = s1.rowNum AND t1.colNum-1 = s1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) s2 ON t1.rowNum = s2.rowNum AND t1.colNum-2 = s2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) s3 ON t1.rowNum = s3.rowNum AND t1.colNum-3 = s3.colNum

/* RIGHT STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) r1 ON t1.rowNum = r1.rowNum AND t1.colNum+1 = r1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) r2 ON t1.rowNum = r2.rowNum AND t1.colNum+2 = r2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) r3 ON t1.rowNum = r3.rowNum AND t1.colNum+3 = r3.colNum

/* UP STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) u1 ON t1.rowNum-1 = u1.rowNum AND t1.colNum = u1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) u2 ON t1.rowNum-2 = u2.rowNum AND t1.colNum = u2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) u3 ON t1.rowNum-3 = u3.rowNum AND t1.colNum = u3.colNum

/* DOWN STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) d1 ON t1.rowNum+1 = d1.rowNum AND t1.colNum = d1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) d2 ON t1.rowNum+2 = d2.rowNum AND t1.colNum = d2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) d3 ON t1.rowNum+3 = d3.rowNum AND t1.colNum = d3.colNum

/* UP LEFT STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) ul1 ON t1.rowNum-1 = ul1.rowNum AND t1.colNum-1 = ul1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) ul2 ON t1.rowNum-2 = ul2.rowNum AND t1.colNum-2 = ul2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) ul3 ON t1.rowNum-3 = ul3.rowNum AND t1.colNum-3 = ul3.colNum

/* UP RIGHT STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) ur1 ON t1.rowNum-1 = ur1.rowNum AND t1.colNum+1 = ur1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) ur2 ON t1.rowNum-2 = ur2.rowNum AND t1.colNum+2 = ur2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) ur3 ON t1.rowNum-3 = ur3.rowNum AND t1.colNum+3 = ur3.colNum

/* DOWN LEFT STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) dl1 ON t1.rowNum+1 = dl1.rowNum AND t1.colNum-1 = dl1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) dl2 ON t1.rowNum+2 = dl2.rowNum AND t1.colNum-2 = dl2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) dl3 ON t1.rowNum+3 = dl3.rowNum AND t1.colNum-3 = dl3.colNum

/* DOWN RIGHT STRING */
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) dr1 ON t1.rowNum+1 = dr1.rowNum AND t1.colNum+1 = dr1.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) dr2 ON t1.rowNum+2 = dr2.rowNum AND t1.colNum+2 = dr2.colNum
LEFT OUTER JOIN (
SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
) dr3 ON t1.rowNum +3= dr3.rowNum AND t1.colNum+3 = dr3.colNum

WHERE t1.charVal = 'x'
--ORDER BY t1.rowNum, t1.colNum
) s1
) s2
*/

/* 
	1799 = Too Low 
	2397 = CORRECT!
*/


/* PART 2 */
/* Instructions2 table. */
DROP TABLE IF EXISTS #tmpInstructions2
CREATE TABLE #tmpInstructions2 (id int identity, instr varchar(max)
, rowNum int, colNum int, charVal varchar(5)
, charsLeft varchar(5), charsRight varchar(5), charsUp varchar(5), charsDown varchar(5)
, charsDiagUpLeft varchar(5), charsDiagUpRight varchar(5), charsDiagDownLeft varchar(5), charsDiagDownRight varchar(5)
)


/*** GENERATE_SERIES FTW! ***/
; WITH s(n) AS (
SELECT value FROM GENERATE_SERIES(1,250,1)
)
INSERT INTO #tmpInstructions2 (rowNum, colNum, charVal)
SELECT t1.rowNum
, CASE WHEN (s.n%LEN(t1.instr)) = 0 THEN LEN(t1.instr) ELSE (s.n%LEN(t1.instr)) END
, SUBSTRING( instr, (s.n),1 )
FROM #tmpInstructions t1
CROSS APPLY s
WHERE s.n <= LEN(t1.instr)
	AND SUBSTRING(instr,(s.n),1) = 'm'

SELECT * FROM #tmpInstructions2

SELECT t2.id, t2.rowNum, t2.colNum, (SELECT ti.instr FROM #tmpInstructions ti WHERE ti.rowNum = t2.rowNum) AS instr
	, (SELECT REVERSE(SUBSTRING(t1.instr,t2.colNum-2,3)) FROM #tmpInstructions ti WHERE ti.rowNum = t2.rowNum) AS charsLeft
	, (SELECT SUBSTRING(t1.instr,t2.colNum,3) FROM #tmpInstructions ti WHERE ti.rowNum = t2.rowNum) AS charsRight

FROM #tmpInstructions2 t2
INNER JOIN #tmpInstructions t1 ON t2.rowNum = t1.rowNum






/* Instructions3 table. */
DROP TABLE IF EXISTS #tmpInstructions3
CREATE TABLE #tmpInstructions3 (id int identity, instr varchar(max)
	, rowNum int, colNum int, aPosRow int, aPosCol int
)

/** Trim up #tmpInstructions2. Clear out non-MAS rows **/
DROP TABLE IF EXISTS #tmpInstructions2a
SELECT *
INTO #tmpInstructions2a
FROM (
	SELECT s1.rowNum, s1.colNum
	, CASE WHEN leftString = 'MAS' THEN 1 ELSE 0 END AS ls
	, CASE WHEN rightString = 'MAS' THEN 1 ELSE 0 END AS rs
	, CASE WHEN upString = 'MAS' THEN 1 ELSE 0 END AS us
	, CASE WHEN downString = 'MAS' THEN 1 ELSE 0 END AS ds
	, CASE WHEN upLeftString = 'MAS' THEN 1 ELSE 0 END AS uls
	, CASE WHEN upRightString = 'MAS' THEN 1 ELSE 0 END AS urs
	, CASE WHEN downleftString = 'MAS' THEN 1 ELSE 0 END AS dls
	, CASE WHEN downRightString = 'MAS' THEN 1 ELSE 0 END AS drs
	FROM (
		/**** UGLY QUERY *****/
		SELECT t1.rowNum, t1.colNum
		, CONCAT(t1.charVal, s1.charVal, s2.charVal) AS leftString
		, CONCAT(t1.charVal, r1.charVal, r2.charVal) AS rightString
		, CONCAT(t1.charVal, u1.charVal, u2.charVal) AS upString
		, CONCAT(t1.charVal, d1.charVal, d2.charVal) AS downString
		, CONCAT(t1.charVal, ul1.charVal, ul2.charVal) AS upleftString
		, CONCAT(t1.charVal, ur1.charVal, ur2.charVal) AS uprightString
		, CONCAT(t1.charVal, dl1.charVal, dl2.charVal) AS downLeftString
		, CONCAT(t1.charVal, dr1.charVal, dr2.charVal) AS downRightString
		SELECT * FROM #tmpInstructions2 t1

		/* LEFT STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) s1 ON t1.rowNum = s1.rowNum AND t1.colNum-1 = s1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) s2 ON t1.rowNum = s2.rowNum AND t1.colNum-2 = s2.colNum

		/* RIGHT STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) r1 ON t1.rowNum = r1.rowNum AND t1.colNum+1 = r1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) r2 ON t1.rowNum = r2.rowNum AND t1.colNum+2 = r2.colNum

		/* UP STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) u1 ON t1.rowNum-1 = u1.rowNum AND t1.colNum = u1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) u2 ON t1.rowNum-2 = u2.rowNum AND t1.colNum = u2.colNum

		/* DOWN STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) d1 ON t1.rowNum+1 = d1.rowNum AND t1.colNum = d1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) d2 ON t1.rowNum+2 = d2.rowNum AND t1.colNum = d2.colNum

		/* UP LEFT STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) ul1 ON t1.rowNum-1 = ul1.rowNum AND t1.colNum-1 = ul1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) ul2 ON t1.rowNum-2 = ul2.rowNum AND t1.colNum-2 = ul2.colNum

		/* UP RIGHT STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) ur1 ON t1.rowNum-1 = ur1.rowNum AND t1.colNum+1 = ur1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) ur2 ON t1.rowNum-2 = ur2.rowNum AND t1.colNum+2 = ur2.colNum

		/* DOWN LEFT STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) dl1 ON t1.rowNum+1 = dl1.rowNum AND t1.colNum-1 = dl1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) dl2 ON t1.rowNum+2 = dl2.rowNum AND t1.colNum-2 = dl2.colNum

		/* DOWN RIGHT STRING */
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) dr1 ON t1.rowNum+1 = dr1.rowNum AND t1.colNum+1 = dr1.colNum
		LEFT OUTER JOIN (
		SELECT id, rowNum, colNum, charVal FROM #tmpInstructions2 t2
		) dr2 ON t1.rowNum+2 = dr2.rowNum AND t1.colNum+2 = dr2.colNum
		WHERE t1.charVal = 'm'
		--ORDER BY t1.rowNum, t1.colNum
	) s1
) s2
WHERE s2.ls=1 OR s2.rs=1 OR s2.us=1 OR s2.ds=1 OR s2.uls=1 OR s2.urs=1 OR s2.dls=1 OR s2.drs=1


--SELECT * FROM #tmpInstructions2a WHERE rowNum =16 AND colNum=135

INSERT INTO #tmpInstructions3 (rowNum, instr, colNum, aPosRow, aPosCol)
SELECT unpvt.rowNum, mPos, unpvt.colNum
	, CASE 
		WHEN mPos IN ('ls','rs') THEN unpvt.rowNum
		WHEN mPos IN ('us','uls','urs') THEN unpvt.rowNum-1
		WHEN mPos IN ('ds','dls','drs') THEN unpvt.rowNum+1
	END AS aRow
	, CASE 
		WHEN mPos IN ('ls','uls','dls') THEN unpvt.colNum-1
		WHEN mPos IN ('rs','urs','drs') THEN unpvt.colNum+1
		WHEN mPos IN ('us','ds') THEN unpvt.colNum
	END AS aCol
FROM (
	SELECT rowNum, colNum, ls, rs, us, ds, uls, urs, dls, drs 
	FROM #tmpInstructions2a
) pvt
UNPIVOT (
	val FOR mPos IN (ls,rs,us,ds,uls,urs,dls,drs)
) unpvt
WHERE unpvt.val = 1

/* CLEANUP. Can't be in first or last row or col */
DELETE FROM #tmpInstructions3 WHERE aPosRow IN (1,140) OR aPosCol IN (1,140)

; WITH ctr AS (
	SELECT * , (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) AS startChar
		, CASE t3.instr
			WHEN 'ls' THEN (SELECT SUBSTRING(instr,t3.colNum-1,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
			WHEN 'rs' THEN (SELECT SUBSTRING(instr,t3.colNum+1,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
			WHEN 'us' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum-1 = t3.rowNum) 
			WHEN 'ds' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum+1 = t3.rowNum) 
			WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-1,1) FROM #tmpInstructions ti WHERE ti.rowNum+1 = t3.rowNum) 
			WHEN 'uls' THEN (SELECT SUBSTRING(instr,t3.colNum+1,1) FROM #tmpInstructions ti WHERE ti.rowNum-1 = t3.rowNum) 
			WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-1,1) FROM #tmpInstructions ti WHERE ti.rowNum+1 = t3.rowNum) 
			WHEN 'drs' THEN (SELECT SUBSTRING(instr,t3.colNum+1,1) FROM #tmpInstructions ti WHERE ti.rowNum-1 = t3.rowNum) 
			ELSE NULL 
		END AS char2
		, CASE t3.instr
			WHEN 'ls' THEN (SELECT SUBSTRING(instr,t3.colNum-2,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
			WHEN 'rs' THEN (SELECT SUBSTRING(instr,t3.colNum+2,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
			WHEN 'us' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum-2 = t3.rowNum) 
			WHEN 'ds' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum+2 = t3.rowNum) 
			WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-2,1) FROM #tmpInstructions ti WHERE ti.rowNum+2 = t3.rowNum) 
			WHEN 'uls' THEN (SELECT SUBSTRING(instr,t3.colNum+2,1) FROM #tmpInstructions ti WHERE ti.rowNum-2 = t3.rowNum) 
			WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-2,1) FROM #tmpInstructions ti WHERE ti.rowNum+2 = t3.rowNum) 
			WHEN 'drs' THEN (SELECT SUBSTRING(instr,t3.colNum+2,1) FROM #tmpInstructions ti WHERE ti.rowNum-2 = t3.rowNum) 
			ELSE NULL 
		END AS char3
	FROM #tmpInstructions3 t3
)
DELETE FROM ctr WHERE startChar <> 'm' OR char2 <> 'a' OR char3 <> 's'

SELECT COUNT(*)
FROM (
	SELECT t1.id AS id1, t1. instr AS instr1, t2.id AS id2, t2.instr AS instr2
		, t1.aPosCol, t1.aPosRow
	FROM #tmpInstructions3 t1
	INNER JOIN #tmpInstructions3 t2 ON t1.aPosRow = t2.aPosRow AND t1.aPosCol = t2.aPosCol
		AND (
			(t2.instr = 'drs' AND t1.instr IN ('dls','urs') ) OR
			(t2.instr = 'dls' AND t1.instr IN ('drs','uls') ) OR

			(t2.instr = 'urs' AND t1.instr IN ('drs','uls') ) OR
			(t2.instr = 'uls' AND t1.instr IN ('dls','urs') ) OR

			(t2.instr = 'ds' AND t1.instr IN ('ls','rs') ) OR
			(t2.instr = 'us' AND t1.instr IN ('ls','rs') ) OR
			(t2.instr = 'ls' AND t1.instr IN ('us','ds') ) OR
			(t2.instr = 'rs' AND t1.instr IN ('us','ds') )
		)
--	WHERE t1.id <> t2.id
) s1
--15,135 & 17,134


SELECT * FROM #tmpInstructions2 ORDER BY id
, (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) AS startChar
	, CASE t3.instr
		WHEN 'ls' THEN (SELECT SUBSTRING(instr,t3.colNum-1,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
		WHEN 'rs' THEN (SELECT SUBSTRING(instr,t3.colNum+1,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
		WHEN 'us' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum-1 = t3.rowNum) 
		WHEN 'ds' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum+1 = t3.rowNum) 
		WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-1,1) FROM #tmpInstructions ti WHERE ti.rowNum+1 = t3.rowNum) 
		WHEN 'uls' THEN (SELECT SUBSTRING(instr,t3.colNum+1,1) FROM #tmpInstructions ti WHERE ti.rowNum-1 = t3.rowNum) 
		WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-1,1) FROM #tmpInstructions ti WHERE ti.rowNum+1 = t3.rowNum) 
		WHEN 'drs' THEN (SELECT SUBSTRING(instr,t3.colNum+1,1) FROM #tmpInstructions ti WHERE ti.rowNum-1 = t3.rowNum) 
		ELSE NULL 
	END AS char2
	, CASE t3.instr
		WHEN 'ls' THEN (SELECT SUBSTRING(instr,t3.colNum-2,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
		WHEN 'rs' THEN (SELECT SUBSTRING(instr,t3.colNum+2,1) FROM #tmpInstructions ti WHERE ti.rowNum = t3.rowNum) 
		WHEN 'us' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum-2 = t3.rowNum) 
		WHEN 'ds' THEN (SELECT SUBSTRING(instr,t3.colNum,1) FROM #tmpInstructions ti WHERE ti.rowNum+2 = t3.rowNum) 
		WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-2,1) FROM #tmpInstructions ti WHERE ti.rowNum+2 = t3.rowNum) 
		WHEN 'uls' THEN (SELECT SUBSTRING(instr,t3.colNum+2,1) FROM #tmpInstructions ti WHERE ti.rowNum-2 = t3.rowNum) 
		WHEN 'dls' THEN (SELECT SUBSTRING(instr,t3.colNum-2,1) FROM #tmpInstructions ti WHERE ti.rowNum+2 = t3.rowNum) 
		WHEN 'drs' THEN (SELECT SUBSTRING(instr,t3.colNum+2,1) FROM #tmpInstructions ti WHERE ti.rowNum-2 = t3.rowNum) 
		ELSE NULL 
	END AS char3
FROM #tmpInstructions3 t3
)
DELETE FROM ctr WHERE startChar <> 'm' OR char2 <> 'a' OR char3 <> 's'






--SELECT * FROM #tmpInstructions2a
--SELECT * FROM #tmpInstructions3 WHERE aPosRow IN (15,17) AND aPosCol IN (135,134)

/*
??? = CORRECT!
*/

/*
NOTES:
Part 1:
For part one, my initial thought is to split the string on each character and then compare characters in
each direction to see which ones spell 'XMAS'.

I may need to add my numbers table finally. :-)

Never mind. I forgot that SQL 2022 significantly improves this need. There's a GENERATE_SERIES virtual
table I can use. https://learn.microsoft.com/en-us/sql/t-sql/functions/generate-series-transact-sql?view=sql-server-ver16

My brain hurts, and I know there's a much cleaner way to do this, but I'm just using a horribly inefficient multiple
LEFT JOIN syntax to check out my strings. We'll have to see if this even works on the final input.

.....

First try through I got a number way too low. But looking at my code, I realized my Number Table wasn't big enough. I was only
generating 100 numbers, but the input is 140x140. I bumped it up and got the right answer.

Resubmit and on to Part 2.


===================================
Part 2:
Part 2 sounds completely insane. I won't have any problem finding the 'MAS'es, but it should
be fun to figure out how many of them cross.

They cross on the A, so I may be able to calculate how many MASes there are and then how many cross on the A.


*/


/********************
--- Day 4: Ceres Search ---
"Looks like the Chief's not here. Next!" One of The Historians pulls out a device and pushes the only button on it. After a brief flash, you recognize the interior of the Ceres monitoring station!

As the search for the Chief continues, a small Elf who lives on the station tugs on your shirt; she'd like to know if you could help her with her word search (your puzzle input). She only has to find one word: XMAS.

This word search allows words to be horizontal, vertical, diagonal, written backwards, or even overlapping other words. It's a little unusual, though, as you don't merely need to find one instance of XMAS - you need to find all of them. Here are a few ways XMAS might appear, where irrelevant characters have been replaced with .:

..X...
.SAMX.
.A..A.
XMAS.S
.X....
The actual word search will be full of letters instead. For example:

MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX
In this word search, XMAS occurs a total of 18 times; here's the same word search again, but where letters not involved in any XMAS have been replaced with .:

....XXMAS.
.SAMXMS...
...S..A...
..A.A.MS.X
XMASAMX.MM
X.....XA.A
S.S.S.S.SS
.A.A.A.A.A
..M.M.M.MM
.X.X.XMASX
Take a look at the little Elf's word search. How many times does XMAS appear?

--- Part Two ---
The Elf looks quizzically at you. Did you misunderstand the assignment?

Looking for the instructions, you flip over the word search to find that this isn't actually an XMAS puzzle; it's an X-MAS puzzle in which you're supposed to find two MAS in the shape of an X. One way to achieve that is like this:

M.S
.A.
M.S
Irrelevant characters have again been replaced with . in the above diagram. Within the X, each MAS can be written forwards or backwards.

Here's the same example from before, but this time all of the X-MASes have been kept instead:

.M.S......
..A..MSMS.
.M.S.MAA..
..A.ASMSM.
.M.S.M....
..........
S.S.S.S.S.
.A.A.A.A..
M.M.M.M.M.
..........
In this example, an X-MAS appears 9 times.

Flip the word search from the instructions back over to the word search side and try again. How many times does an X-MAS appear?
*/